#!/bin/sh

function whatthecommit() {
    message="$(curl -s -L http://whatthecommit.com/ | tail -n9 | head -n1| sed -e 's/<p>//')"

    echo "$message (y/n/q)?"
    read answer

    case "$answer" in
        Y|y)
            git commit -m "$message"
            exit 0
        ;;
        n) 
            whatthecommit
        ;;

        q)
            exit 0
        ;;
        *)
            whatthecommit
        ;;
    esac
}

whatthecommit




